### ISSUE TITLE
Can't install for Yii2

### ISSUE THREAD

**Issue by alexeykuznec** [mikejacobson/jquery-bootstrap-scrolling-tabs#1]
I try:
composer require bower-asset/jquery-bootstrap-scrolling-tabs
and catch:

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Can only install one of: bower-asset/bootstrap[v3.1.1, v3.3.5].
    - Can only install one of: bower-asset/bootstrap[v3.1.1, v3.3.5].
    - Can only install one of: bower-asset/bootstrap[v3.1.1, v3.3.5].
    - bower-asset/jquery-bootstrap-scrolling-tabs v0.0.4 requires bower-asset/bootstrap ~3.1.1 -> satisfiable by
    - Installation request for bower-asset/jquery-bootstrap-scrolling-tabs ^0.0.4 -> satisfiable by bower-asset/j
    - Installation request for bower-asset/bootstrap (locked at v3.3.5) -> satisfiable by bower-asset/bootstrap[v

Installation failed, reverting ./composer.json to its original content.

**Comment by mikejacobson** [comment]
Hopefully v0.0.5 fixes this issue for you. I'm guessing you already had bootstrap v3.3.5, and I had the bootstrap dependency set at ~3.1.1, which wouldn't allow any version above 3.1.*.

I don't think I had a reason for locking it at 3.1.*, so I changed it to accept 3.*.*. I tested it and it works fine.
