### ISSUE TITLE
Reverse the scrolling actions

### ISSUE THREAD

**Issue by bkd** [mikejacobson/jquery-bootstrap-scrolling-tabs#10]
Hi Mike
I'm aware of settings but it would be ideal to reverse the scroll actions. On a mobile device or a small screen the left arrow should scroll the available tabs to the left instead. It might be good to have an option to reverse the scrolling setting, just my 2 cents!
Cheers
B

**Comment by mikejacobson** [comment]
Good suggestion. I'll add that option.

**Comment by mikejacobson** [comment]
For v0.2.0 I added a reverse-scroll option. Just pass in option `reverseScroll: true`.

Details in the README [here](https://github.com/mikejacobson/jquery-bootstrap-scrolling-tabs#ft0).
