### ISSUE TITLE
Add callback function on tab click

### ISSUE THREAD

**Issue by nelwa** [mikejacobson/jquery-bootstrap-scrolling-tabs#11]
Hi, Nice plugin, I really like it.
Would it be possible to add an optional custom callback function that gets called when a tab is either clicked or touched?
Thanks
nelwa

**Comment by mikejacobson** [comment]
Sure, I can add that. Good suggestion!

**Comment by mikejacobson** [comment]
v0.5.0 adds this feature. Details in the README [here](https://github.com/mikejacobson/jquery-bootstrap-scrolling-tabs#tabClickHandler).

Just pass in your callback function using the `tabClickHandler` option.
