### ISSUE TITLE
Add options for arrow

### ISSUE THREAD

**Issue by anardil** [mikejacobson/jquery-bootstrap-scrolling-tabs#12]
Hi,

Nice plugin!
I would like to use the font-awesome icons instead of glyphicon.
Is it possible to add the possibility to give in options the html for the arrows?

Thanks.

**Comment by mikejacobson** [comment]
v0.6.0 adds the option to customize the `class` properties of the scroll arrows.

Details in the README [here](https://github.com/mikejacobson/jquery-bootstrap-scrolling-tabs/#cssClassArrows).

Will that give you what you need?

**Comment by anardil** [comment]
Yes perfect!
Thanks a lot.
