### ISSUE TITLE
Arrows position: absolute

### ISSUE THREAD

**Issue by elalemanyo** [mikejacobson/jquery-bootstrap-scrolling-tabs#14]
Hi,
Will be possible to put the arrows position absolute and than make .scrtabs-tabs-fixed-container width 100%.
Like this when one arrow is disable can be just disappear and more width will be used. Also the arrows can have a background color with some transparency and user see where the tabs are going.

Is maybe possible to do it all a new setting?

Thanks!

**Comment by mikejacobson** [comment]
Interesting suggestions. I'll look into this. Thanks!
