### ISSUE TITLE
Custom Scroll Arrow Content

### ISSUE THREAD

**Issue by elalemanyo** [mikejacobson/jquery-bootstrap-scrolling-tabs#15]
Hallo,
Maybe will be interesting adding the possibility to set the arrow content, like this would be possible to use als arrow icon a symbol from an svg ([SVG `symbol` a Good Choice for Icons](https://css-tricks.com/svg-symbol-good-choice-icons/)). For the moment the option Custom Scroll Arrow Class is not enough. Right now I am fixing my problem like this:

```
$('#tabs-inside-here').scrollingTabs().on('ready.scrtabs', function() {
  $('.scrtabs-tab-scroll-arrow-right .glyphicon-chevron-right').html('<svg class="icon"><use xlink:href="#arrow-right" /></svg>');
  $('.scrtabs-tab-scroll-arrow-left .glyphicon-chevron-left').html('<svg class="icon"><use xlink:href="#arrow-left" /></svg>');
});
```

Or do I am missing something and there is a better way?

Maybe something like this:
```
$('#tabs-inside-here').scrollingTabs({
  LeftArrowContent: '<svg class="icon"><use xlink:href="#arrow-left" /></svg>',
  RightArrowContent: '<svg class="icon"><use xlink:href="#arrow-right" /></svg>',
});
```

Thanks!

**Comment by mikejacobson** [comment]
The way you're doing it now is currently the only way.

I like your idea, though, of optionally passing in html strings to use for the arrows. I can add that.

Thanks for the suggestion!

**Comment by mikejacobson** [comment]
Sorry this took so long, but v1.2.0 adds this option. Details are in the README here:
https://github.com/mikejacobson/jquery-bootstrap-scrolling-tabs#customArrowsContent

And here's a plunk showing it working with custom svg icons:
http://plnkr.co/edit/2MdZCAnLyeU40shxaol3?p=preview

Thanks again for the suggestion! I hope it works for you.

**Comment by elalemanyo** [comment]
👍
