### ISSUE TITLE
bootstrap 4

### ISSUE THREAD

**Issue by roydekleijn** [mikejacobson/jquery-bootstrap-scrolling-tabs#17]
What about the compatibility with bootstrap 4 ?

we need to add list-inline class to the ul element

Also the active class doesn't change if you click on the tabs.. so, you can only visit the tab once

**Comment by mikejacobson** [comment]
I put together a plunk showing the plugin working with Bootstrap 4:
http://plnkr.co/edit/xy9RPd53LcbAArgYmhFh

The plunk's README has the steps I followed to make it work. It was fairly straightforward and didn't require too many changes. And there doesn't seem to be any issue with visiting a tab more than once.

**Comment by robsdedude** [comment]
However, the plunk does not how to easily migrate the data driven use case. It would be much easier if there were a `customLiClass` and a `customAClass` option or something like it. While using `tabsLiContent` and/or `tabsPostProcessors` seems like it could be a workaround, it's cumbersome and hard if the tabs data (i.e. `myTabs` in the README) changes dynamically.
