### ISSUE TITLE
jump tabs that already is visible

### ISSUE THREAD

**Issue by chrisokamoto** [mikejacobson/jquery-bootstrap-scrolling-tabs#18]
I have a lot of tabs like 1 2 3 ... 100
The first time I enter the page, I see tabs from 1 to 20, for example.. I wanted that when I click on the next arrow, see tabs 21-40.. I don't  want to see the tabs that was already visible before I clicked the next arrow. Is that a way to do this? I tried drecreasing the SCROLL_OFFSET_FRACTION but it didn't work the way I wanted too..

**Comment by mikejacobson** [comment]
Sorry for the delayed response--I haven't had a chance to work on this lately.

You were on the right track. I think to achieve what you want, you'd need to set SCROLL_OFFSET_FRACTION to something like 1 or 1.1 (setting it to 1 might make it scroll a bit too far each time), and also remove the mousedown and mouseup listeners, so scrolling only occurs on click.

Here's a plunk with those changes:
http://plnkr.co/edit/06WrrSk5Ue6QWHMaQ0E9?p=preview

In addition to setting the `SCROLL_OFFSET_FRACTION` to `1.1`, I also commented out the mousedown and mouseup listeners (lines 372, 373, 378, and 379).
