### ISSUE TITLE
the windows is smaller, tab's arrows is below

### ISSUE THREAD

**Issue by NisanurBulut** [mikejacobson/jquery-bootstrap-scrolling-tabs#20]
![ekran alintisi](https://cloud.githubusercontent.com/assets/9026717/24330629/6995bfe8-122b-11e7-8c47-73753dc9b69f.PNG)

`<div class="row">
                
        
                    <div class="scrolling-tabs-container">
                    <div scrolling-tabs-wrapper watch-tabs="GroupAndProductCtrl.groups" refresh-on="GroupAndProductCtrl.triggerRefresh">
                            <uib-tabset>
                                <uib-tab ng-repeat="group in groups" heading="{{group.adi}}" ng-click="ClikGroup(group.id)"></uib-tab>
                            </uib-tabset>
                        </div>
                      
                    </div>
              
            </div>`

//script

 $scope.triggerRefresh = false;

    function forceARefresh() {
        $scope.triggerRefresh = true;
        $timeout(function () {
            $scope.triggerRefresh = false;
        });
    }

**Comment by mikejacobson** [comment]
Closing this as it is an issue with the angular directive, not the jquery plugin, and is being tracked in that repo now.
