### ISSUE TITLE
Boostrap Scrollable Swipe Tab View Feature

### ISSUE THREAD

**Issue by kampiamodikuesto** [mikejacobson/jquery-bootstrap-scrolling-tabs#21]
hi, i would like to know is possible to realize that 

https://codepen.io/gbhasha/pen/gaggRR

with jquery-bootstrap-scrolling-tabs script.

**Comment by mikejacobson** [comment]
Are you wanting to combine the two--have the tabs scroll using this plugin, and have the content panels fly in using that `slick` plugin?

I can't say for sure without actually building it, but I suspect it could work. Bootstrap has baked-in functionality for activating a panel when its tab is clicked, so you'd need to override that with the `slick` plugin's functionality.

**Comment by kampiamodikuesto** [comment]
i haven’t combine slick with bootstrap tap, i need something similar slick but tabs focused and with a little support by the author:)

**Comment by ankitinnodel** [comment]
@kampiamodikuesto I Have used this solution **https://codepen.io/gbhasha/pen/gaggRR** and I want to make infinite looping for the tab. So Is there any right solution you have https://codepen.io/Innodel/pen/GRJZKZN. please let me know if you have the right solution.
Thanks
