### ISSUE TITLE
Active tab even on reload

### ISSUE THREAD

**Issue by mjanthrax** [mikejacobson/jquery-bootstrap-scrolling-tabs#23]
Hello, can someone give me a hint or help to make my specific tab active even after a page reload.

**Comment by mikejacobson** [comment]
To persist the tab state on page reload, you'd need to either write some code yourself that sets location.hash when tabs are clicked, and listens for the [onhashchange event](https://developer.mozilla.org/en-US/docs/Web/API/WindowEventHandlers/onhashchange), as described in this blog post:
http://www.aidanlister.com/2014/03/persisting-the-tab-state-in-bootstrap/

or use a plugin like the one the guy who wrote that blog post created:
https://github.com/aidanlister/jquery-stickytabs
