### ISSUE TITLE
disabled state does not update when using data-driven tabs

### ISSUE THREAD

**Issue by chlab** [mikejacobson/jquery-bootstrap-scrolling-tabs#27]
I am creating a wizard where you can click through a number of tabs step by step. Initially, they're all disabled and when you click next, the next tab is enabled and activated.

When changing the `disabled` state of the tabs definition and calling `refresh`, everything seems to update except for the disabled state.

How to reproduce:

1. open http://plnkr.co/edit/x3LOMxSygSonL2XqGbVQ?p=preview
2. Note that tab with index 1 is disabled
3. Click "Update Tab"
4. Tab with index 1 gets updated (including `disabled: false`) but is still disabled

**Comment by mikejacobson** [comment]
Oops, you're right! Sorry about that. v1.2.1 should fix this issue.

Here's a fork of your plunk showing it working: http://plnkr.co/edit/qrzzY1PA6UjfCKlka33B?p=preview

**Comment by chlab** [comment]
Cool, thx for fixing this so quickly @mikejacobson
