### ISSUE TITLE
Nested bootstrap .nav > .tab-content conflict

### ISSUE THREAD

**Issue by xautlx** [mikejacobson/jquery-bootstrap-scrolling-tabs#28]
if put one nested bootstrap .nav component in the jquery-bootstrap-scrolling-tabs content div, refreshDataDrivenTabs will append scrolling tab pane to the nested .nav > .tab-content div redundantly.

FYI: my workaround is change the code in the jquery.scrolling-tabs.js  from '$currTabContentPanesContainer = $container.find('.tab-content')' to '$currTabContentPanesContainer = $container.find(' > .tab-content')'

**Comment by mikejacobson** [comment]
With your workaround, do the tabs actually function correctly?

Per the [Bootstrap docs](http://getbootstrap.com/javascript/#tabs), nested tabs are not supported, and so my plugin also doesn't support them.

I just added a note to the README indicating this.

**Comment by xautlx** [comment]
I did a simple test with this workaround and it worked fine. Of course, I'm not sure it really resolve the problem or  support nested tabs.
