### ISSUE TITLE
dropdown problem

### ISSUE THREAD

**Issue by serdartaylan** [mikejacobson/jquery-bootstrap-scrolling-tabs#3]
hello
dropdown problem.
example link : http://plnkr.co/edit/yEhaLiYZQGYB8k2uTfSX?p=preview

**Comment by mikejacobson** [comment]
Ah, yes, the dropdown menu is hidden inside the fixed container, which has `overflow: hidden`.

Unfortunately, the Bootstrap dropdown doesn't have a built-in "append-to-body" option so I'll have to do it manually. I'll fix this.

**Comment by mikejacobson** [comment]
v0.0.8 should fix this issue. [Here's a plunk](http://plnkr.co/edit/DpUJPXhHmr9B5OpdNDxx?p=preview) showing it working with dropdowns.

That was kind of a tricky one. :)
