### ISSUE TITLE
enableSwiping and scrolling with arrows not working

### ISSUE THREAD

**Issue by michalchovanak** [mikejacobson/jquery-bootstrap-scrolling-tabs#31]
Hi, i've noticed on mobile screens that if i use scroll arrow to move tabs and then use swipe to go back, its not working. You can try it in your demo i found. Swiping should be probably handled by code not css. Can you please look at this issue?

**Comment by mikejacobson** [comment]
Ah, yes, I see the problem. I'll fix this. Thanks!

**Comment by mikejacobson** [comment]
v2.0.0 should fix this issue. Thanks for bringing it to my attention.

I agree with your suggestion that swiping should be handled by code, and I implemented the fix that way. It's working much better now. Thanks! :thumbsup:
