### ISSUE TITLE
Resize does not update all tab panels

### ISSUE THREAD

**Issue by RussNZ** [mikejacobson/jquery-bootstrap-scrolling-tabs#33]
Hi, I have two scrolling tabs on my page, both of them are initialized and scroll etc.

The problem is when the window is resized, only one of the tabs gets refreshed.

Any help appreciated, thanks.

**Comment by mikejacobson** [comment]
Ooh, I see the problem. I'll fix it.

**Comment by mikejacobson** [comment]
v2.0.1 should fix this issue.

**Comment by RussNZ** [comment]
Yep, that's fixed it. 

Thanks for the speedy fix, cheers.

**Comment by mikejacobson** [comment]
Stupendous! Glad it's working now. :thumbsup:
