### ISSUE TITLE
Right to Left tabs

### ISSUE THREAD

**Issue by sinasaeedi** [mikejacobson/jquery-bootstrap-scrolling-tabs#34]
Hello there.
Thanks for your great work.
Is there any solution to use tabs in RTL direction?

There are two problems to resolve:
1- Tabs direction
2- Arrow keys functionality

The first problem is resolvable using CSS.
But the second one is the real problem.

If you want to make a quick test, replace `<html>` with this line:
`<html lang="fa" dir="rtl">`
This resolves the first problem.

**Comment by mikejacobson** [comment]
I'm looking into this. I have it partly working right now.

**Comment by mikejacobson** [comment]
OK, so I think v2.1.0 will support RTL, but this is my first foray into this area so I could be wrong. Let me know if it doesn't work in your real-life application.

Details are in the README [here](https://github.com/mikejacobson/jquery-bootstrap-scrolling-tabs#enableRtlSupport).

And you might also want to enable option `reverseScroll`(details [here](https://github.com/mikejacobson/jquery-bootstrap-scrolling-tabs#reverseScroll)) to make it more intuitive for your situation, but I'm not sure.

Thanks for using my little plugin! 😃

**Comment by sinasaeedi** [comment]
Well man, thank you! The RTL support works like a charm.
In my case it also needs to add `reverseScroll`, like you said.
Thank you 👍
