### ISSUE TITLE
multiple difrent HTML-defined tabs not working right

### ISSUE THREAD

**Issue by NovaYear** [mikejacobson/jquery-bootstrap-scrolling-tabs#37]
im trying use multiple instance scrolling abs whit HTML-defined tabs, first tab instance is ok not problem, second tab instance header not rendered true.
first tab nistance include 6 tabs, second tab instance include 2 tabs and not visible.
is problem scrtabs-tabs-fixed-container and scrtabs-tabs-movable-container width not calculating true.
suggested fix change calculate system unique container name. do not use global class based select and calculate..

**Comment by NovaYear** [comment]
see this secreenshots:
![resim](https://user-images.githubusercontent.com/31353203/29723352-ef9a1ee0-89cc-11e7-9452-204f9100caa1.png)

![resim](https://user-images.githubusercontent.com/31353203/29723559-b5ae38be-89cd-11e7-82c3-9a06241f5b25.png)

**Comment by mikejacobson** [comment]
Based on the screenshots, it looks like you have nested tabs&mdash;the second set of tabs is nested inside the first set.

Is that the case? If so, that's the problem because [nested tabs are not supported](https://getbootstrap.com/docs/3.3/javascript/#tabs).

**Comment by NovaYear** [comment]
bro, i found a solution;
add on change event for nested tabs, click a tab and view another tab content auto refresh scrollingTabs header.. 

```
$('a[data-toggle="tab"]').on('shown.bs.tab', function (e) {
   $('.nav-tabs').scrollingTabs('refresh');
});
```

**Comment by mikejacobson** [comment]
Nice one! Glad you figured out a solution. :thumbsup:
