### ISSUE TITLE
Last Tab in the Movable Scrolling bar was hide after complete scrolling 

### ISSUE THREAD

**Issue by rajendra001** [mikejacobson/jquery-bootstrap-scrolling-tabs#4]
Hide the last tab by using the jquery-bootstrap-scrolling-tabs plugin. I debugging it, Hiding tab was in the firebug. i change the scrtabs-tabs-movable-container width dynamically then it works fine. If any other changes need to plugin level . i mean in min.js file.

<div class="scrtabs-tabs-movable-container" style="left: -201px; width: 1320px;">

**Comment by mikejacobson** [comment]
Can you make a plunkr that demonstrates the issue? I don't really understand the problem.

If you're adding tabs dynamically, you need to call `refresh` to resize the tabs container after adding/removing a tab.
