### ISSUE TITLE
HTML replaced not reused

### ISSUE THREAD

**Issue by Saqib-Shakil** [mikejacobson/jquery-bootstrap-scrolling-tabs#42]
I have been trying to use your component with react and after a lot of messing around I was able to determine that this plugin does not use the orignal html rather duplicate it there for removing any events binded to it. Is there any work around for it

**Comment by mikejacobson** [comment]
If you need to execute your own custom code when a tab is clicked, you can pass in option `tabClickHandler` when initializing the plugin. Details in the README [here](https://github.com/mikejacobson/jquery-bootstrap-scrolling-tabs#tabClickHandler).
