### ISSUE TITLE
Double arrows on left and right

### ISSUE THREAD

**Issue by genachka** [mikejacobson/jquery-bootstrap-scrolling-tabs#46]
I'm getting left arrows and when I scroll all the way to the right I get two right arrows.
![bootstrap-scroll-tabs](https://user-images.githubusercontent.com/7947294/32409529-0895c162-c184-11e7-99b4-4a57657a6071.png)

I don't have this issue when I do it using Data-Driven approach but can't use that until I know how to do what's described in #45

**Comment by mikejacobson** [comment]
Can you put together a plunk that demonstrates the issue? It's difficult to troubleshoot without knowing how you're using the plugin.

**Comment by genachka** [comment]
Using Aurelia frontend framework and the tabs are part of a component so not going to be easy to create a plunk for it. If I can get #45 working, where this doesn't happen, I'd be ok with that.
