### ISSUE TITLE
Scrolling tab not working for tabs inside tabs

### ISSUE THREAD

**Issue by DanielZambranoC** [mikejacobson/jquery-bootstrap-scrolling-tabs#47]
![image](https://user-images.githubusercontent.com/28786672/32579587-f22b1cc4-c4b7-11e7-9a12-9f7aab4a14ac.png)

I have a tabs inside tabs, and it its only working on the parent one, I've set the same class for each group of tabs so one call make the magic, it works like a charm, but no on the child tabs.

What can I do?
```
$(function() {
    $('.nav-tabs').scrollingTabs();
});
```

**Comment by mikejacobson** [comment]
Unfortunately, [Bootstrap tabs](https://getbootstrap.com/docs/3.3/javascript/#tabs) do not support nested tabs.

**Comment by DanielZambranoC** [comment]
**Workaround**
`$('.nav-tabs:first').scrollingTabs();`

I will elaborate more in the future so it can detect and initialize diferent instances of tabs with scrollingTab. Thanks @mikejacobson for this great plugin!.
