### ISSUE TITLE
hidden popover

### ISSUE THREAD

**Issue by aloredoa** [mikejacobson/jquery-bootstrap-scrolling-tabs#49]
Hi Mike, I have started to use your plugin and has helped me enough, just that I have a detail, I want to implement some popover's within a tab but it appears hidden within nav-tabs. I want to implement something similar as you did with the dropdown menu but I do not know if it is a good idea, what can I do?

Thanks a lot

**Comment by mikejacobson** [comment]
The `container` option for popovers allows you to specify an element the popover should be appended to. (By default, it's appended to the parent of the element triggering the popover, so it ends up a sibling of the triggering element.)

So in your case, you could, for example, specify `data-container="body"` and the popover will be appended to the body and so will not be within the nav-tabs.

[Here's a plunk](http://plnkr.co/edit/HKFHpmm3Ub33BN0DiLWA?p=preview) with an example of how to do that. In Tab 2 I added an element that triggers a popover on hover.

Does this help? Is this what you're trying to accomplish?

**Comment by aloredoa** [comment]
Yes, that is precisely what I was looking for, thank you very much for the information.

**Comment by mikejacobson** [comment]
Stupendous! Glad to have helped.
