### ISSUE TITLE
unable of click at first tab after click at other tab

### ISSUE THREAD

**Issue by leandroruel** [mikejacobson/jquery-bootstrap-scrolling-tabs#5]
the first tab is not clickable anymore after i clicked at other tabs. tested that at my enviroment.

**Comment by mikejacobson** [comment]
Can you put together a plunk demonstrating the issue? In my plunks showing the plugin working, the first tab is still clickable after clicking other tabs.

**Comment by leandroruel** [comment]
hi, after a few minutes i notice that is not a bug of this plugin, i made a mistake, calling tabs with js 
```js
$('.nav-tabs a[href="#tab-1"]').tab('show');
```

but i already set the data attribute on it, so the js was not necessary, i removed it and worked fine. sorry for that and i'm closing it.

**Comment by mikejacobson** [comment]
Excellent! Glad it's working for you now.
