### ISSUE TITLE
Programmatically select tab

### ISSUE THREAD

**Issue by dilipvinu** [mikejacobson/jquery-bootstrap-scrolling-tabs#50]
Can you select a tab programmatically?

**Comment by mikejacobson** [comment]
Yes, you can. You would need to do something like this:
```javascript
$('a[href="#tab9"').trigger('click');
$('.nav-tabs').scrollingTabs('refresh');
```
Triggering the click on the tab will make that tab active, then calling the `refresh` method on the plugin will scroll the newly active tab into view.

Here's a plunk demonstrating how to do it--in `st-demo.js`, I just trigger tab9 to become active after a 3-second delay:
http://plnkr.co/edit/Zjtfy0tCejIOIgm1YZT7?p=preview
