### ISSUE TITLE
forceActiveTab working in BS 4?

### ISSUE THREAD

**Issue by 185driver** [mikejacobson/jquery-bootstrap-scrolling-tabs#51]
Mike, this is quite a handy library! Thanks very much.

Scrolling-tabs is working well for me with BS 4 (beta3) except that the `forceActiveTab: true` option doesn't seem to be honored. I created a codepen to illustrate at https://codepen.io/185driver/pen/KZeZOJ.

`$('.nav-tabs').scrollingTabs('scrollToActiveTab');` does seem to work, however. Am I missing something with how I'm setting the options?

What I'm really shooting for is to use scrolling-tabs with the bootstrap-material-design library since a scrolling tab is included in Google's design. I have a codepen for it at https://codepen.io/185driver/pen/zpaRqv/.  If I can get the forceActiveTab option working with it, I'm on my way.  Unfortunately, even `$('.nav-tabs').scrollingTabs('scrollToActiveTab');` isn't working in combination with their library so I'm double out-of-luck.

Any advice or pointing in a good direction appreciated as able.

Kind regards,
Doug

**Comment by mikejacobson** [comment]
Hmm, strange. I'll look into this.

**Comment by mikejacobson** [comment]
Looking at your codepen, you're using html-defined tabs, not data-driven tabs. The `forceActiveTab` option is for data-driven tabs. When you call `refresh` with that option, the plugin will set the active tab in the UI to whatever tab is set to active based on its current data. So it doesn't really apply if your tabs are not data-driven.

**Comment by 185driver** [comment]
Oh! I'm sorry I didn't notice that. I will need to consider a code change then since not having the active tab fully displayed on screen is odd-looking. Thanks for your time, Mike.

**Comment by 185driver** [comment]
I'd like to revisit this issue if possible now that I've created a codepen using data-driven tabs instead. No markup or custom css was used for the tabs, though I am using my own markup for the tab contents. The pen is here: https://codepen.io/185driver/pen/RxEPZN.

For me the `forceActiveTab` option is still not working (that I can see). Clicking on a tab makes it active, but the tab doesn't pull into view if it is partially hidden when clicked.

I also note several differences from the html markup mode:
1. The tab set to be active in the myTabs array isn't set to active when the page is loaded. It only gets an 'active' class when clicked.
2. The tab heights do not match the arrow heights.
3. The tabsLiContent option is nice, and allows for the `nav-item` class to be added back in manually, but there is no similar feature provided for the anchor links. Typically, Bootstrap expects those elements to have a `nav-link` class, which appears to affect the tabs appearance (apparently causes issues as described in #1 and #2 above). If I add:
```
.on('ready.scrtabs', () => {
    $('.nav-tabs li a').addClass('nav-link');
  });
```
when initializing scrolling-tabs, the tab heights are displayed normal height and the correct tab is set to 'active'.

It would be handy if the data-driven mode would automatically add these `nav-` classes where they typically appear in Bootstrap, but my real question continues to be how to get the `forceActiveTab` option to work.  Thanks for your help.

**Comment by mikejacobson** [comment]
If I'm understanding you correctly, I think this might be what you're looking for. Here's a fork of your original pen:
https://codepen.io/mikejacobson/pen/wpNdWB

The tabs are HTML-defined BS4. When you click on a tab that's partially hidden, it will be automatically scrolled into view. Is that the goal?

It's just listening for clicks on the tabs, and when a click occurs, after a short timeout to give the clicked tab time to get its `active` class set, it calls the scrollingTabs `scrollToActiveTab` method.

I think that's the method/option you were looking for, not `forceActiveTab`. `forceActiveTab` is strictly for setting the active tab DOM element based on the underlying tabs data, not for scrolling it into view.

**Comment by 185driver** [comment]
Yes, that's it! I misread the readme for that feature. Apologies. It's working as expected now with html-markup option in BS4. Thank you.

Now that I'm squared away, a couple of questions for you:
1. When I close this issue, would you like me to move my BS4 vs BS3 data-driven tabs differences observations mentioned above into a new issue for your reference, or skip that?
2. As I mentioned in my first comment above, what I'm really shooting for is to use scrolling-tabs with bootstrap-material-design, and my codepen for that is at: https://codepen.io/185driver/pen/zpaRqv. I've added the setTimeout() for scrolling to the active tab there too. It works for scrolling to the active tab when clicking on partially-displayed tabs on the left end, but not for partially-displayed tabs on the right end. I realize this is beyond a typical BS4 use-case scenario, but if you had any insight on why it's only working in one direction, I'd be grateful. 

Thanks again!

**Comment by mikejacobson** [comment]
Excellent! Glad it's working for you now.

Regarding support for data-driven BS4 tabs, if you don't actually need that feature at this point, I'd say don't open a new issue for it. I appreciate that you documented the differences, and having them here for reference is good enough.

And, just out of curiosity, do the built-in material design scrollable tabs not provide all the functionality you need? Is that why you're using this plugin?

**Comment by 185driver** [comment]
Copy that. Thanks.

I'm using [bootstrap-material-design](https://fezvrasta.github.io/bootstrap-material-design/docs/4.0/material-design/) which is a materialized version of BS4. Their nav tabs component doesn't include a scroller, same as BS4. Your utility is a real boon for those wanting to complete the 'materialization' of their Bootstrap tabs. Now if I can just find a way to [adjust the arrow div widths](https://github.com/mikejacobson/jquery-bootstrap-scrolling-tabs/issues/52) I'll be all set.

Kind regards,
Doug

**Comment by mikejacobson** [comment]
Ah, I see. Well I'm glad my plugin is able to provide some value.
