### ISSUE TITLE
 widthMultiplier:  to larger value?

### ISSUE THREAD

**Issue by waynep16** [mikejacobson/jquery-bootstrap-scrolling-tabs#56]
For some reason my tabs are only ever around 70% of the wrapper, 

even with  widthMultiplier: 1 its still around 70%

if i can use  something like  widthMultiplier: 1.5  that would solve my issue

or somehow fix why my tabs are not going full width of the wrapper?

**Comment by mikejacobson** [comment]
Would you be able to put together a plunk or something similar that demonstrates the issue? I'd be happy to help, but I can't provide much assistance without seeing your particular implementation.

**Comment by waynep16** [comment]
Hard to do a plunk as there is a lot going on within this application - I can tell you that the code being used is 

A) in a modal (i am doing update/refresh on modal show) 

B) tabs are within a list item row 

C) here is a screenshot showing the tabs do not span full width and the width 

https://snag.gy/wXh70N.jpg

You can see the scrolling tabs about half way down the screnshot and I resize my browser then magically it comes to 100% but initial load of the modal is is only about 70% as per screenshot  - is there another way to force refreshing the view so it goes 100% ?

**Comment by mikejacobson** [comment]
You can force a refresh by calling the plugin's `refresh` method:
```javascript
$('.nav-tabs').scrollingTabs('refresh');
```

**Comment by waynep16** [comment]
yes i already have this in place on modal shown 

```
$('#ready_to_send').on('shown.bs.modal', function (e) {
     $('.multi-message-tabs').scrollingTabs('refresh');
```

But it doesnt refresh untill i resize and scale the browser window

**Comment by mikejacobson** [comment]
Maybe try wrapping the refresh call in a `setTimeout` with a delay of 100 or so? The modal elements might just need some time to fully settle after the `shown` event fires.

**Comment by waynep16** [comment]
BINGO - that did the trick 

Code if anyone needs it 

`$('#ready_to_send').on('shown.bs.modal', function (e) {
setTimeout(function(){
  $('.multi-message-tabs').scrollingTabs('refresh');  // refresh scrolling tabs
}, 300);
 });`

**Comment by mikejacobson** [comment]
Thanks for sharing the code for others who might need it! 👍
