### ISSUE TITLE
Misbehaves with dynamic theme loading

### ISSUE THREAD

**Issue by centurianii** [mikejacobson/jquery-bootstrap-scrolling-tabs#57]
Many things don't work when we load dynamically different bootstrap themes, like:
1. tabs are missing (in photo tab-19, tab-20),

2. tabs exist but last one don't flash right at the end,

3. scroll button loses position.

I keep the right order of libraries in every test: like `/lib/plugins/bootstrap.3.3.7/sandstone-theme.css` and then `/lib/plugins/srctabs/jquery.scrolling-tabs.css`.

The [photo](https://ibb.co/fSWhQJ).

**Comment by mikejacobson** [comment]
Would you be able to put together a plunk or something that demonstrates the issue? That would greatly help with troubleshooting.

Are the different themes loaded via user interaction, by selecting the theme from a dropdown or something like that? If so, you might just need to [trigger a refresh](https://github.com/mikejacobson/jquery-bootstrap-scrolling-tabs#forcing-a-refresh) of the tabs after the new theme has loaded, and possibly trigger the refresh after a small timeout to be sure the elements have settled and are ready for their sizes to be checked.

**Comment by mikejacobson** [comment]
I'm glad you found a solution that works for you.

This project was originally created to support IE8+, which is why a simpler CSS solution using transforms or flexbox was not an option.
