### ISSUE TITLE
Queries regarding usage

### ISSUE THREAD

**Issue by umar1990** [mikejacobson/jquery-bootstrap-scrolling-tabs#6]
Is there a way to activate a particular tab using the scrollingTabs api?

We have implemented shortcut keys in our application for tabs. Ex if the user presses number 4 in keyboard we need to activate the 4th Tab. As of now i am doing something like this 
`funtion tabSelection(event){
  var keyPressed =  event.data;
			  var tabNum = 0;
			  $('.nav-tabs > li').each(function() {
				  if(tabNum == keyPressed){
					  $(this).children('a').trigger('click');
				  }
				  tabNum++;
			  });
}`

The issue with above code is if multiple tabs are opened and i am in 15th tab and i press a shortcut key 2.
The second tab is selected but its not visible in the tabs bar.. Basically its not scrolling to active tab.
How to scroll to active tab

**Comment by mikejacobson** [comment]
There's currently no way to force a scroll to the active tab, but I'll add a way. That would be a nice feature.

**Comment by mikejacobson** [comment]
v0.1.0 adds the `scrollToActiveTab` method so you can programmatically force a scroll to the active tab anytime.
