### ISSUE TITLE
Scrolling Tabs width 0 when inside bootstrap modal 

### ISSUE THREAD

**Issue by sathyaprakash94** [mikejacobson/jquery-bootstrap-scrolling-tabs#63]
Hi
Good plugin, I tried to apply the plugin inside the Bootstap modal. Its working fine but scrtabs-tabs-fixed-container width "0" when open the modal. The width is applying only on page resize.  The working link is as below.
[Codepen Link](https://codepen.io/WebTechie/pen/pYEMNv?editors=0010)

**Comment by mikejacobson** [comment]
What you can do is call the plugin's `refresh` method when the modal's `shown.bs.modal` event fires:
```javascript
$('.nav-tabs').scrollingTabs('refresh');
```

[Here's a fork of your pen](https://codepen.io/mikejacobson/pen/ywMBJO?editors=0010) showing it in action.

**Comment by sathyaprakash94** [comment]
Thanks @mikejacobson, I hope its working.

**Comment by mikejacobson** [comment]
Oh, and thanks for putting together the pen demonstrating the issue! It makes troubleshooting much easier. 👍

**Comment by sathyaprakash94** [comment]
Thanks a lot.

**Comment by lcjury** [comment]
Mike, is there any plan on using a `MutationObserver` to refresh the plugin when it becomes visible?

**Comment by mikejacobson** [comment]
@lcjury , no, no plans for that currently. There's already a way for users of the plugin to refresh it if necessary for their particular implementations.
