### ISSUE TITLE
Can't revisit tabs that were visited before initializing the Scrolling Tabs

### ISSUE THREAD

**Issue by MiroslavGrozdanovski** [mikejacobson/jquery-bootstrap-scrolling-tabs#65]
Any tabs that were visited before initializing the Scrolling Tabs can't be opened after calling the plugin. Here is a Plunk that is showing the [issue](http://plnkr.co/edit/Lz3zmb3K8zy7QWGMhmwX?p=preview). Just click on a different tab and try to go back to "Tab Number 2".

As you can see in the JS file, I called `click()` before calling the plugin, but the same issue is happening if you call Bootstrap's `tab('show')` method. We actually run into the issue by calling the `tab('show')` method in order to show the correct tab depending on the URL. The reason why we cannot move the initialization of the plugin before our `tab('show')` call is because all the HTML elements are hidden and we only make them visible after the correct tab is selected. On the other side, this plugin expects the Tabs to be visible in order to calculate the needed widths.

The reasons why this is happening is combination of these two:

- On the first activation of a tab, Bootstrap stores the pointer to the Anchor element in a [data](https://api.jquery.com/data/) property. It then reuses the same element on the next click.

- This plugin clones the tab elements while initializing

So when you try to navigate back to the "Tab Number 2", Bootstrap tries to activate the element it stored in the data property, which doesn't actually exist on the HTML page anymore.

I really like your library, so we kept using it and fixed this issue by clearing out the specific data property that Bootstrap stores (it's the same for Bootstrap 3 and 4) after the tab elements are cloned. It still works because next time the tab is clicked, Bootstrap will store the correct element, which is exactly what happens for the other tabs that weren't visited before this plugin was initialized. 

@mikejacobson let me know what you think and I can send a PR with our fix.

**Comment by mikejacobson** [comment]
Wow, your debugging and fix are very impressive. It's somewhat of an edge case but I would love to see your PR with the fix. Please go ahead and submit it when you get a chance. Thanks for using my plugin!
