### ISSUE TITLE
Starting broken

### ISSUE THREAD

**Issue by giolvani** [mikejacobson/jquery-bootstrap-scrolling-tabs#7]
The plugin doesn't work correctly when it is start with fews tabs.
![image](https://cloud.githubusercontent.com/assets/2387872/20179934/711b6fe4-a73f-11e6-9129-547a4cea486c.png)

But, if you resize the window to a smaler size enabling scrolling feature, it works correctly.
![image](https://cloud.githubusercontent.com/assets/2387872/20179864/3243e580-a73f-11e6-963f-406a780a2091.png)

Even if you resize the window to a larger size again.
![image](https://cloud.githubusercontent.com/assets/2387872/20179899/56147f92-a73f-11e6-97f5-e8c5919258a0.png)

**Comment by mikejacobson** [comment]
Oops, sorry about that. v0.1.1 should fix this issue.

**Comment by giolvani** [comment]
Thanks Mike!

Seems that just add "display:none", to class .scrtabs-tab-scroll-arrow. At least, this workaround works for me... ;)
