### ISSUE TITLE
dynamically added tab page click not working.

### ISSUE THREAD

**Issue by ssutar934** [mikejacobson/jquery-bootstrap-scrolling-tabs#72]
Hello,
Please suggest me how to add new tab page in 'HTML-defined Tabs'.

thanks in advance.

**Comment by mikejacobson** [comment]
Here's a plunk demonstrating adding a tab (Tab Number 11) and its tab-pane and then refreshing the plugin:
http://plnkr.co/edit/M4ofcV2XNNAb0m4jUoZn

This is the code that does it (it's in st-demo.js):
```js
setTimeout(() => {
  console.log('----> Appending Tab Number 11');
  $('ul.nav-tabs').append('<li role="presentation"><a href="#tab11" role="tab" data-toggle="tab">Tab Number 11 (NEW!)</a></li>');
  $('.tab-content').append('<div role="tabpanel" class="tab-pane" id="tab11">Tab 11 (NEW!) content...</div>');
  $('.nav-tabs').scrollingTabs('refresh');
}, 10);
```

I wrapped it in a `setTimeout` to give the plugin time to initialize before adding the new tab.

Is that what you're trying to accomplish?

**Comment by ssutar934** [comment]
Thank you Mike.
It's working fine.

**Comment by mikejacobson** [comment]
Excellent! Glad to hear it's working for you now. 👍
