### ISSUE TITLE
Accessibility for Keyboard Users

### ISSUE THREAD

**Issue by peterslc** [mikejacobson/jquery-bootstrap-scrolling-tabs#78]
Hey Mike,

First off, awesome plugin! Thanks so much for sharing.

I've been trying to make it accessible to keyboard users. I'm not too concerned about scrolling with tab focus, although that would be the proper way to make it fully accessible. What I'm trying to do is make it so you can tab to the arrows and hit "enter" and have the same behavior as a click.

I made the arrows tabbable:
`$('.scrtabs-tab-scroll-arrow').attr('tabindex', '0');`

But I'm not sure what event I should call when hitting enter to make it scroll:
`$('.scrtabs-tab-scroll-arrow-right').keypress(function() {
    if (event.which == 13) {
      // not sure what to put here...
    }
});`
(then a similar one for the left arrow)

This is probably the wrong way to go about it, but I'm incredibly new to JS and JQuery. If you have time to provide some assistance I'd really appreciate it, as would anyone working towards an accessible world wide web :-)

Regardless, thanks again—you rock! 👍

**Comment by mikejacobson** [comment]
You could listen for `keydown` and `keyup` events on the scroll arrows ([keypress](https://developer.mozilla.org/en-US/docs/Web/API/Document/keypress_event) is deprecated) and use those to programmatically trigger `mousedown` and `mouseup` events, which the plugin listens for:

```js
$('.scrtabs-tab-scroll-arrow')
  .attr('tabindex', '0')
  .on('keydown', function(e) {
    if (e.which === 13) {
      $(this).mousedown();
    }
  })
  .on('keyup', function(e) {
    if (e.which === 13) {
      $(this).mouseup();
    }
  });
```

That way, holding down `Enter` would simulate holding down the mouse button.

Here's a plunk showing it working. I added that code in `st-demo.js` in the `ready.scrtabs` handler:
https://plnkr.co/edit/e9S5EAhEOuz3cnwkNAaU

Thanks for using my plugin!

**Comment by peterslc** [comment]
You're awesome, thanks for the quick response and the help! Keyboard users everywhere say thanks :)

**Comment by mikejacobson** [comment]
Ha! Thanks! I hope the Keyboard Users Everywhere community shares your exuberance. 😺
