### ISSUE TITLE
Is this possible to use without bootstrap ??

### ISSUE THREAD

**Issue by Anzil-Aufait** [mikejacobson/jquery-bootstrap-scrolling-tabs#79]
How can i use this one without using bootstrap files ??

**Comment by mikejacobson** [comment]
Sorry, you can't. The plugin is specifically built to enhance Bootstrap tabs and is dependent upon their markup and functionality.

**Comment by Anzil-Aufait** [comment]
@mikejacobson , Thank you for the replay.
