### ISSUE TITLE
Resize container width with more flexible not just window

### ISSUE THREAD

**Issue by stantoxt** [mikejacobson/jquery-bootstrap-scrolling-tabs#8]
I think resizing container width denpending on some element more just window would be more flexible and convenient for applying to web.

**Comment by mikejacobson** [comment]
Unfortunately, DOM elements don't have a resize event to hook into. There are some libraries out there that poll for size changes using requestAnimationFrame and setTimeout, but I'm not sure how reliable they are and how much overhead it would add. I'll look into it.

**Comment by stantoxt** [comment]
Thanks.I make some change that add extended divided number.

`$.fn.scrollingTabs.defaults = {
    tabs: null,
    propPaneId: 'paneId',
    propTitle: 'title',
    propActive: 'active',
    propDisabled: 'disabled',
    propContent: 'content',
    ignoreTabPanes: false,
    scrollToTabEdge: false,
    disableScrollArrowsOnFullyScrolled: false,
    forceActiveTab: false,
    widthDividend: 2.6
  };`

`function ScrollingTabsControl($tabsContainer) {
    var stc = this;
    stc.$tabsContainer = $tabsContainer;
    stc.movableContainerLeftPos = 0;
    stc.scrollArrowsVisible = false;
    stc.scrollToTabEdge = false;
    stc.disableScrollArrowsOnFullyScrolled = false;
    stc.widthDividend = 2.6;
    stc.scrollMovement = new ScrollMovement(stc);
    stc.eventHandlers = new EventHandlers(stc);
    stc.elementsHandler = new ElementsHandler(stc);
  }`

`p.setElementWidths = function () {
        var ehd = this,
         stc = ehd.stc;
        stc.containerWidth = stc.$tabsContainer.outerWidth() / stc.widthDividend;
        stc.winWidth = stc.$win.width();
        stc.scrollArrowsCombinedWidth = stc.$leftScrollArrow.outerWidth() + stc.$rightScrollArrow.outerWidth();
        ehd.setFixedContainerWidth();
        ehd.setMovableContainerWidth();
      };`

My code is bad. I hope you can make this feature more elegant.

**Comment by mikejacobson** [comment]
Ah, so your tabs are in a section of the page that is always a set fraction of the width of the window? So hooking into the window resize event can still work, you just need the calculated widths to take into account that fraction of the window width?

If that's the case, then that's a simpler feature to add. You pretty much already did it! :)

I was thinking you wanted support for tabs inside resizable panels within the page, which would require monitoring the sizes of those panel elements somehow, which is a much bigger change.

**Comment by mikejacobson** [comment]
v0.3.0 adds a `widthMultiplier` option. Passing in a multiplier like 0.5 or 0.75 seemed more intuitive to me than passing in a dividend.

More details in the README [here](https://github.com/mikejacobson/jquery-bootstrap-scrolling-tabs#widthMultiplier).

I hope this gives you what you need. Sorry it took so long.

**Comment by stantoxt** [comment]
Wow!That is awesome.I love this feature.I will give you my feedback.By the way,that is cool. @mikejacobson .Thanks.

**Comment by stantoxt** [comment]
The widthMultiplier Option Works great.
```
$('.navbar .nav-tabs').scrollingTabs({scrollToTabEdge: true,widthMultiplier: 0.45})
                .on('ready.scrtabs', function () {$('.tab-content').show();});
```
![final picture](https://github.com/stantoxt/MarkdownResource/raw/master/pictures/bootstrapTabWithMultiple.png)

**Thanks @mikejacobson .**

**Comment by mikejacobson** [comment]
Excellent! Glad to hear it.

And thanks for the screenshot! It's nice to see how this is being used in the wild. Your site looks really nice.

Mike
