### ISSUE TITLE
Save scrolled position

### ISSUE THREAD

**Issue by P-T-I** [mikejacobson/jquery-bootstrap-scrolling-tabs#83]
First of all, thanks for this project, looks very nice!

Is it possible to access the current scrolled position and return to it programmatically?

Let's say I'm currently on a tab where I need to scroll to; somewhere on the far right of the total amount of tabs. External changes need me to re-initialize the scrolling tabs and basically 'resets' the scrolling to the far left. I can off-course 're-click' the formerly active tab with jquery, but I also would like to automatically 're-scroll' to the position of the this tab, is this possible?

Hopes this makes sense to you..

**Comment by P-T-I** [comment]
Sry, missed the 

```
$('.nav-tabs').scrollingTabs('scrollToActiveTab');
```

**Comment by P-T-I** [comment]
Tried the:
``` 
$('.nav-tabs').scrollingTabs('scrollToActiveTab');
``` 
That isn't working for me

**Comment by mikejacobson** [comment]
Would you be able to put together something that demonstrates your scenario and `scrollToActiveTab` not working?

Here's a codepen showing it working: https://codepen.io/mikejacobson/pen/eYVYLLK
After a small delay, it programmatically selects Tab 15 and then scrolls to it using `scrollToActiveTab`.

Maybe you could use that as a starting point?

It's difficult to troubleshoot without seeing how you're using it, but you might want to try calling `scrollToActiveTab` after a slight delay using `setTimeout`—maybe the tabs just need a moment to stabilize after the new tab is selected and before `scrollToActiveTab` is called?

**Comment by P-T-I** [comment]
Mike; Thanks so much... It was a typical case of RTFM.... I needed to set the correct Bootstrap version in the settings.... Bootstrap 3 sets the 'active' class different then Bootstrap 4 (or later) does. Setting 'Bootstrap: 4' in the init settings totally did the trick!
